services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: front-prod
    # env_file: .env.prod
    command: npm run start:prod
    restart: unless-stopped
    environment:
      VITE_API_URL: /api
