services:
  front-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front-test
    environment:
      VITE_API_URL: http://localhost:3000
    entrypoint: ['npm', 'run', 'test']
